name: after_layout
description: Execute code after the first layout of your widget has been performed, i.e. after the first frame has been displayed.
version: 1.0.7+1
authors:
 - Flutter Community <community@flutter.zone>
 - Simon Lightfoot <simon@devangels.london>
homepage: https://github.com/fluttercommunity/flutter_after_layout
maintainer: Simon Lightfoot (@slightfoot)

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.0.0
  flutter_web_test: any
  
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
